# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea9f2c0b464e3d04f1387642b4c2f86d13b2a1c077606ad886cb848b24d6162ff538d620b12272988add1ad4b6f2eef2f887ed5d48b5665a37cd01b97110834

test:
  secret_key_base: 6b6dee207a8b4389792b77eae0556b1d8f5d05a6e781bdeb81a8f8eff9bc802ad69686cc5288ca5f7eb3708707f94de736b78d63191094ee09bf5ee8caab1299

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
